/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author nacer
 */
public class menu116 extends javax.swing.JFrame {

    /**
     * Creates new form menu116
     */
    public menu116() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bar à salade");
        setPreferredSize(new java.awt.Dimension(730, 713));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Suplément Topping Extra (6dhs)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Petite");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Moyenne");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Grande");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Salade verte");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Mélange varié");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 109, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Pâte");
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Riz");
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jCheckBox8.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("Sans base");
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("Pomme de terre");
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 117, -1));

        jCheckBox10.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("Tomate cerise");
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 117, -1));

        jCheckBox11.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("Oeuf dur");
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 117, -1));

        jCheckBox12.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("Tomate");
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 117, -1));

        jCheckBox13.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("Betterave");
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 117, -1));

        jCheckBox14.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setText("Carottes rapées");
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 117, -1));

        jCheckBox15.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setText("Concombres");
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 117, -1));

        jCheckBox16.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setText("Poivron vert/rouge");
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jCheckBox17.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setText("Haricot rouge");
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 117, -1));

        jCheckBox18.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setText("Chou blanc");
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 117, -1));

        jCheckBox19.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setText("Fonds d'artichaut");
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 117, -1));

        jCheckBox20.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setText("Oignon");
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 117, -1));

        jCheckBox21.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox21.setText("Cacahuéte");
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 117, -1));

        jCheckBox22.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setText("Cerneaux de noix");
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 117, -1));

        jCheckBox23.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox23.setText("Vinaigrette moutarde");
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 750, -1, -1));

        jCheckBox24.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox24.setText("Huile d'olive");
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        jCheckBox25.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox25.setText("Mozzarelle");
        jPanel1.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 117, -1));

        jCheckBox26.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox26.setText("Tomates confites");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 117, -1));

        jCheckBox27.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox27.setText("Dinde fumée");
        jPanel1.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 117, -1));

        jCheckBox28.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox28.setText("Lentilles");
        jPanel1.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 117, -1));

        jCheckBox29.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox29.setText("Cornichon");
        jPanel1.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 117, -1));

        jCheckBox30.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox30.setText("Raisins secs");
        jPanel1.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 117, -1));

        jCheckBox31.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox31.setText("Pousses de soja");
        jPanel1.add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 117, -1));

        jCheckBox32.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox32.setText("Haricot vert");
        jPanel1.add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 117, -1));

        jCheckBox33.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox33.setText("Orange");
        jPanel1.add(jCheckBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 117, -1));

        jCheckBox34.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox34.setText("Kiwi");
        jPanel1.add(jCheckBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 117, -1));

        jCheckBox35.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox35.setText("Pomme");
        jPanel1.add(jCheckBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 117, -1));

        jCheckBox36.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox36.setText("Radis");
        jPanel1.add(jCheckBox36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 117, -1));

        jCheckBox37.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox37.setText("Croûtons à l'ail");
        jPanel1.add(jCheckBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 117, -1));

        jCheckBox38.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox38.setText("Olives vertes");
        jPanel1.add(jCheckBox38, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 117, -1));

        jCheckBox39.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox39.setText("Olives noires");
        jPanel1.add(jCheckBox39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 117, -1));

        jCheckBox40.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox40.setText("Huile d'olive + citron");
        jCheckBox40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox40ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, -1, -1));

        jCheckBox41.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox41.setText("Huile d'olive & vinaigre balsamique");
        jPanel1.add(jCheckBox41, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, -1, -1));

        jCheckBox42.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox42.setText("Pesto");
        jPanel1.add(jCheckBox42, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, -1, -1));

        jCheckBox43.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox43.setText("Mayonnaise");
        jPanel1.add(jCheckBox43, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 710, -1, -1));

        jCheckBox44.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox44.setText("Sans sauce");
        jPanel1.add(jCheckBox44, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 750, -1, -1));

        jCheckBox45.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox45.setText("Sauce césare");
        jPanel1.add(jCheckBox45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 750, -1, -1));

        jCheckBox46.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox46.setText("Huile d'argan");
        jPanel1.add(jCheckBox46, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 750, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox58.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox58.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox58.setText("Campignons frais");
        jPanel2.add(jCheckBox58, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 319, 113, -1));

        jCheckBox57.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox57.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox57.setText("Poivrons marinés");
        jPanel2.add(jCheckBox57, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, 113, -1));

        jCheckBox56.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox56.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox56.setText("Coeur de palmier");
        jPanel2.add(jCheckBox56, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 267, 113, -1));

        jCheckBox47.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox47.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox47.setText("Poulet grillé     50g");
        jPanel2.add(jCheckBox47, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        jCheckBox48.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox48.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox48.setText("Crevettes");
        jPanel2.add(jCheckBox48, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 113, -1));

        jCheckBox49.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox49.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox49.setText("Surimi");
        jPanel2.add(jCheckBox49, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 113, -1));

        jCheckBox54.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox54.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox54.setText("Avocat");
        jPanel2.add(jCheckBox54, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 215, 113, -1));

        jCheckBox50.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox50.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox50.setText("Thon");
        jPanel2.add(jCheckBox50, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, 113, -1));

        jCheckBox51.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox51.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox51.setText("Jambon de boeuf");
        jPanel2.add(jCheckBox51, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 137, 113, -1));

        jCheckBox52.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox52.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox52.setText("Emmenthal");
        jPanel2.add(jCheckBox52, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 163, 113, -1));

        jCheckBox55.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox55.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox55.setText("Maïs");
        jPanel2.add(jCheckBox55, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, 113, -1));

        jCheckBox53.setBackground(new java.awt.Color(255, 153, 0));
        jCheckBox53.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox53.setText("Fromage rouge");
        jPanel2.add(jCheckBox53, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 113, -1));

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Topping Extra");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 140, 360));

        jLabel4.setText("Maximum 5 ingredients + 1 Topping Extra");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 270, 20));

        jLabel5.setText("Maximum 8 ingredients + 2 Topping Extra");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 280, 20));

        jLabel6.setText("Ingerdients au choix + 4 Topping Extra");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 240, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Sauce");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 70, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Base");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Ingredients");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 700, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 700, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Composez Votre Salade");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacer\\Desktop\\logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox40ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu116().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
